services:
  lambda:
    image: python:3.14.6-alpine
    networks:
      - localstack_network
    volumes:
      - ${LAMBDA_DIR}:/var/task
    working_dir: /var/task
    command: sh -c "pip install --quiet -r requirements.txt && python ${LAMBDA_PATH}"

networks:
  localstack_network:
    external: true
